### ISSUE TITLE
Stocks

### ISSUE THREAD

**Issue by Shootcity** [averwhy/EconomyX#5]
Are we able to add our owns stocks and create our own stock market for our discord?

**Comment by averwhy** [comment]
Stocks are global, if you create one anyone can invest in it who has access to the bot
it can be done via `e$stock create [name]`.

**Comment by Shootcity** [comment]
Thanks for the speedy reply! 
Oh cool, I'm trying to find a bot that makes a stock market for a discord server. Do you have a full command list available?

**Comment by averwhy** [comment]
Yes:
All commands start with `e$`
for example, `e$bet 100`

bet - Bets money. There is a 50/50 chance on winning and losing.
rockpaperscissors - Rock paper scissor game. amount is money you want to bet, and choice must be rock, paper, or scissor (singular, no 's)
prefix - Views the prefix you use with the bot. Note that this is only per-user.
roulette - Roulette gambling command. Starts a propmpt in which the user reacts with the color they wish to bet.
profile - Views your profile. Can also view another users profile. They must be in the database.
help - Shows this message
work - Work. You earn a random number between 1 and 500.
register - Creates a profile with EconomyX. You can also use this is delete your account/profile.
customize - The customize command.
info - Shows bot information and statistics.
support - no help :(
pay - no help :(
bal - no help :(
rob - no help :(
invite - Returns a link that you can use to invite EconomyX to your server.
lottery - Base lottery command. Views active lottery stats.
uptime - Shows the uptime for EconomyX
portfolio - Views a players stock portfolio. Includes all investments, and owned stocks.
ping - Shows EconomyX's latency/connection to Discord.
stock - Stocks management commands. Invoking without a command shows list of top stocks.
news - no help :(
leaderboard - Views a leaderboard of users, sorted by their balance, descending.
source - Gets the source on github for any command.
privacy_policy - An interactive command to view EconomyX's Privacy Policy.
guess - Guess game with money. You have 5 chances to guess the number randomly chosen between 1-10.
This amounts to a 50/50 chance.
invest - The base command for investments.
Invoking invest without a subcommand allows you to invest in stocks.
